# Generated by Django 4.2.5 on 2023-10-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_token_tokenproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.DeleteModel(
            name='TokenProxy',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
