# Generated by Django 4.2.5 on 2023-11-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='subservice',
            field=models.ManyToManyField(related_name='subservices', to='book.subservice'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='book.service'),
        ),
    ]
